### ISSUE TITLE
Track Crashed

### ISSUE THREAD

**Issue by julianfrancodev** [EgehanGundogdu/ulauncher-covid19#1]
Report Crashed Covid 19 Track on Ulauncher 5.8 and Extension API 2.0.0

**Comment by EgehanGundogdu** [comment]
The api response scheme used seems to have changed. I'll fix it soon. Thanks for feedback!

**Comment by EgehanGundogdu** [comment]
As I guessed, the api scheme has changed. everything works again. stay healthy!
