### ISSUE TITLE
Feature request: Clarify source or sources of information

### ISSUE THREAD

**Issue by phillipprado** [EgehanGundogdu/ulauncher-covid19#2]
This is genuinely a high quality ulauncher extension, and I find it very useful. The only downside is that I can't seem to find the source(s) used to list out the information. I think this should be made clear where the information is coming from in the readme so anyone who uses it can know and trust that the data is accurate and trustworthy.

**Comment by EgehanGundogdu** [comment]
Hi Phillip. Thanks for feedback. Required changes applied to the readme file. Stay healthy!
